#!/bin/bash

# omarchy:summary=Open the app set for a work/relax/socialize mode
# omarchy:args=[work|relax|socialize]

set -euo pipefail

mode=${1:-}
if [[ -z $mode ]]; then
 mode=$(omarchy-menu-select "Mode" code relax socialize tetris study work eat) || exit 0 
fi

case $mode in
  code)
    omarchy launch browser "https://github.com/Menjadianjay"
    sleep 1
    omarchy launch browser "https://notion.so"
    omarchy launch webapp "https://www.youtube.com/results?search_query=rnb+music+playlist"
    omarchy agent &
    gtk-launch code.desktop
    ;;

  relax)
    omarchy launch browser
    sleep 1
    omarchy launch webapp "https://www.youtube.com"
    ;;

  socialize)
    genres=(keshi rnb lany "2016 edm")
    genre=${genres[RANDOM % ${#genres[@]}]}

    omarchy launch browser
    sleep 1
    omarchy launch webapp "https://www.youtube.com/results?search_query=${genre// /+}+music+playlist"
    gtk-launch WhatsApp.desktop
    gtk-launch Discord.desktop
    ;;

  tetris)
    omarchy launch webapp "https://www.youtube.com/watch?v=CDBL_JjoC1M"
    sleep 1 
    gtk-launch tetrio-desktop.desktop
    ;;
  
  study)
    omarchy launch browser "https://github.com/Menjadianjay"
    sleep 1
    omarchy launch webapp "https://www.youtube.com"
    sleep 1
    gtk-launch obsidian.desktop
    ;;

  work)
    omarchy launch browser "https://mail.google.com"
    omarchy launch browser "https://github.com/Menjadianjay"
    omarchy launch browser "https://notion.so"
    sleep 1
    omarchy launch webapp "https://www.youtube.com"
    sleep 1 
    gtk-launch obsidian.desktop
    ;;

  eat)
    omarchy launch browser "https://tv12.lk21official.cc/"
    ;;

  *)
    echo "Usage: mode [code|relax|socialize|tetris|study|work|eat]" >&2
    exit 1
    ;;
esac
